### ISSUE TITLE
Invalid path to apiconfig.yaml

### ISSUE THREAD

**Issue by DenisOgr** [allegroai/trains-server-k8s#23]
I have run to test two versions of deployment: docker-compose and Kubernetes (not Helm). I used this [documentation](https://allegro.ai/clearml/docs/rst/deploying_clearml/deploying_clearml_formats/index.html)

I met a problem with defining fixed used apiconfig.yaml described [here](https://allegro.ai/clearml/docs/docs/deploying_clearml/clearml_server_config.html#web-login-authentication)

On both versions I used the same approach - I created the file` /opt/clearml/config/apiserver.conf` on the host machine.  Docker composer version worked fine, but the Kubernetes version did not. 
After a while, I have found some differences between docker volume definitions:

docker-compose : 
```
volumes:
    - /opt/clearml/logs:/var/log/trains
    - /opt/clearml/config:/opt/trains/config
```
Kubernetes:
```
volumeMounts:
        - mountPath: /var/log/clearml
          name: apiserver-hostpath0
        - mountPath: /opt/clearml/config
          name: apiserver-hostpath1
      restartPolicy: Always
      nodeSelector:
        app: clearml
      volumes:
      - name: apiserver-hostpath0
        hostPath:
          path: /opt/clearml/logs
      - name: apiserver-hostpath1
        hostPath:
          path: /opt/clearml/config
```
So in docker-composer used /opt/**trains**/config, but in Kubernetes /opt/**clearml**/config

I changed Kubernetes `mountPath` for   `apiserver-hostpath1` in the [file-line](https://github.com/allegroai/clearml-server-k8s/blob/master/clearml-server-k8s/base/apiserver-deployment.yaml#L98) and it works fine now.

Is it an issue or I missed something?
